version: '3.8'

services:
  nef-emulator:
    build: ./nef-emulator
    ports:
      - "8080:8080"
    environment:
      - SOME_ENV_VAR=value
    volumes:
      - ./nef-emulator/config:/app/config

  ml-af:
    build: ./ml-af
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    depends_on:
      - nef-emulator

  capif:
    build: ./capif
    ports:
      - "9000:9000"
    environment:
      - OAUTH2_SECRET=your_secret