name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libhdf5-dev \
            libffi-dev \
            libcairo2 \
            libpango-1.0-0 \
            libjpeg-dev \
            git

      - name: Install Python dependencies
        run: python -m pip install -r thesis/requirements.txt

      - name: Run tests
        run: |
          mkdir -p CI-CD_reports
          pytest --cov | tee CI-CD_reports/coverage_${{ github.run_number }}.txt
