name: Check unused Python code

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/unused-code.yml'
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/unused-code.yml'

jobs:
  vulture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-

      - name: Install vulture
        run: pip install vulture

      - name: Run vulture
        id: vulture
        run: |
          mkdir -p CI-CD_reports
          report="CI-CD_reports/vulture_report_${{ github.run_number }}.txt"
          if [ -f .vulture-ignore ]; then
            IGNORE_NAMES=$(paste -sd, .vulture-ignore)
            EXTRA_ARGS="--ignore-names $IGNORE_NAMES"
          fi
          vulture --min-confidence 90 --exclude '*/tests/*' $EXTRA_ARGS . > "$report"
          if [ -s "$report" ]; then
            echo "unused=true" >> "$GITHUB_OUTPUT"
            cat "$report"
          else
            echo "unused=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload vulture report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vulture_report_${{ github.run_number }}
          path: CI-CD_reports/vulture_report_${{ github.run_number }}.txt

      - name: Trim old reports
        if: always()
        run: |
          ls -1t CI-CD_reports/vulture_report_*.txt | tail -n +6 | xargs -r rm

      - name: Fail if unused code detected
        if: steps.vulture.outputs.unused == 'true'
        run: |
          echo "Unused code detected."
          exit 1
